image: node:buster

stages:
  - test
  - deploy
  - postdeploy

# test:
#   stage: test
#   image: node:alpine
#   before_script:
#     - yarn
#   script:
#     - yarn test
#   artifacts:
#     when: always
#     paths:
#       - coverage
#     expire_in: 30 days
#   rules:
#     - if: $CI_COMMIT_BRANCH != "master"

lint:
  stage: test
  image: node:buster
  before_script:
    - yarn
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
