image: node:16-buster

stages:
  - test
  - build
  - deploy
  - postdeploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_BRANCH != "master"

test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn jest ./src --coverage
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  coverage: /All files\s*\|\s*([\d\.]+)/

e2e:
  image: cypress/browsers:node16.5.0-chrome97-ff96
  stage: test
  before_script:
    - yarn
    - yarn cypress install --force
  script:
    - yarn test:e2e --headless --record --key $CYPRESS_RECORD_KEY
  artifacts:
    when: always
    paths:
      - tests/e2e/videos/**/*.mp4
      - tests/e2e/screenshots/**/*.png
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

build-image-semiprod:
  image: docker:latest
  stage: build
  script:
    - cp .env_semi .env
    - docker login -u $docker_login -p $docker_pass
    - docker build -t escolasoft/***REMOVED***plstoreadmin:semiprod .
    - docker push escolasoft/***REMOVED***plstoreadmin:semiprod
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: tcp://docker:2375
    VERSION: '1.5.6'
  services:
    - name: docker:dind
      alias: docker
