image: node:16-buster

stages:
  - test
  - deploy
  - postdeploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_BRANCH != "master"

test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn jest ./src --coverage
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  coverage: /All files\s*\|\s*([\d\.]+)/

e2e:
  image: cypress/browsers:node16.5.0-chrome97-ff96
  stage: test
  before_script:
    - yarn
  script:
    - yarn test:e2e --headless --record --key $CYPRESS_RECORD_KEY
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"
