image: node:16-buster

stages:
  - test
  - build
  - deploy
  - postdeploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_BRANCH != "master"

test-unit:
  stage: test
  before_script:
    - yarn
  script:
    - yarn jest ./src --coverage
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  coverage: /All files\s*\|\s*([\d\.]+)/

test-e2e:
  image: cypress/browsers:node16.5.0-chrome97-ff96
  stage: test
  before_script:
    - yarn
    - yarn cypress install --force
  script:
    - yarn test:e2e --headless --record --key $CYPRESS_RECORD_KEY
  artifacts:
    when: always
    paths:
      - tests/e2e/videos/**/*.mp4
      - tests/e2e/screenshots/**/*.png
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
