name: Run Docker image build and tag
on:
  push:
    tags:
      - '*'
jobs:
  run:
    runs-on: docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.PASSWORD }}
      - name: Build Docker image
        run: docker build -t heseya/admin:${{ github.ref_name }} .
      - name: Push Docker image
        run: docker push heseya/admin:${{ github.ref_name }}
